name: postgres-service

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
        PostgreSQL:
            image: postgres:11
            ports:
               - 5432: 5432
            env:
              POSTGRES_USER: user
              POSTGRES_PASSWORD: pass
              POSTGRES_DB: test_db

    steps:
      - name: install netcat
        run: sudo apt-get update && sudo apt-get install netcat -y

      - name: wait for postgres service to start
        run: |
              echo "Waitin for postgreSQL to start..."
              while ! nc -z localhost 5432; do
                echo "Postgres is starting..."
                sleep 1
                done
                echo "PostgreSQL started successfully"

