name: Python install

on: [push]

jobs:
  build:
    runs-on: ubuntu latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.9'
